### ISSUE TITLE
All item 99 ISSUE

### ISSUE THREAD

**Issue by JoelAlexanderProg** [turtle-insect/StarOcean2#2]
The option "all item 99" causes crashes whenever you want to sell something, maybe if you set it to some value like 10 or anything less than 20 it could work, also as other guy mentioned, there are some problems with story progression when you activate the item option, but it could also be because the items are exceeding their maximum capacity at 99 and not necessarily because they are key items.
For the rest everything is perfect, a few days ago I lost all my progress during a blackout so this tool is super helpful, thanks.

**Comment by turtle-insect** [comment]
suppot
https://github.com/turtle-insect/StarOcean2/commit/de0c7c2279e4b7bfaa94d18cd0a3cf35ed6fb6c0

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/StarOcean2/commit/65300572a0754658422b060edfca4696bb95b58b
