### ISSUE TITLE
Request for "Exp" to be 8 digits long.

### ISSUE THREAD

**Issue by ttran913** [turtle-insect/StarOcean2#3]
The current "Exp" field's max is 9,999,999. Since the max level is 255, getting to 255 requires about 81,405,400+ exp points, even with combat skill "effort" on. So the request is to just make that "Exp" field go up to 99,999,999.

**Comment by turtle-insect** [comment]
support
https://github.com/turtle-insect/StarOcean2/commit/d32ae82991391d305ee8bc6a0a2592dcf7a6d56e

**Comment by ttran913** [comment]
Thank you!
