### ISSUE TITLE
Some info that might be of use to your . 

### ISSUE THREAD

**Issue by SkillerCMP** [turtle-insect/StarOcean2#4]
SW - Star Ocean The Second Story R
https://docs.google.com/spreadsheets/d/1FBkLqn542IIYeFAg3fF1c6W6-pi6ympMFjsJGogquqI

Note that with items Weapons and stuff can Be place in the normal Items Section like we show in the IDS_ItemAddresses but really they should be placed in there own address starting at offset 
0000FFD4  	Equipment Item Section ( as single items)

Feel free to use any information that you would like,  your Editor works for both Ps4/Switch im being told .. 
If you end up using stuff just drop a Credit link to the Sheet thats all we ask .. 

nice work

**Comment by turtle-insect** [comment]
https://github.com/turtle-insect/StarOcean2/commit/65300572a0754658422b060edfca4696bb95b58b
